- redisgraph/client.py
- setup.py
1. created new class QueryResult which will contain the data and the
statistics from the query. Will also contain a pretty_print method to
print the info.
2. corresponding changes in query method
> change returned value from the query

- redisgraph/client.py
- redisgraph/query_result.py
- setup.py
Moved the ResultQuery class and exposed the statistics data as properties.
(Those changes in redisgraph-py and redis-graph will work also without the changes in the C code because it will retrieve the data as 0s)
> Expose the statistics data as properties

- redisgraph/client.py
- redisgraph/query_result.py
I had to tweak a couple things to get this running in python 3 - tested in 2.7.13 for backwards compatibility.
> Python3 compatibility

- redisgraph/client.py
In Python 2 byte format  is treated as string 
but In python version 3 .. they are separate 
and while running redisgraph .. data elements are in bytes format in the code and 
python is thowing error with commit command  as 
`TypeError: a bytes-like object is required, not 'str' `
so i think we  need to use 
result_set = [res.*decode()*.split(',') for res in data] 
to make it compatible with python version 3 instead of 
result_set = [res.split(',') for res in data]
> to support python3

- redisgraph/client.py
https://github.com/RedisLabs/redisgraph-py/issues/15
Feature to merge node or relation added
USAGE:
```
tim = Node(label='person', alias=client.random_string(), properties={'name': 'Tim Doe', 'age': 25, 'gender': 'male', 'status': 'single'})
redis_graph.merge(tim)
tom = Node(label='person', properties={'name': 'Tom Doe', 'age': 23, 'gender': 'male', 'status': 'single'})
japan = Node(label='country', properties={'name': 'Japan'})
redis_graph.merge("""%s-[v:visited {purpose: "work"}]->%s"""%(tom,japan))
```
> Issue #15: MERGE support added

- redisgraph/query_result.py
Pass `edge_id` while parsing the edge data.
As seen in the [Relationship uniqueness in patterns](https://oss.redislabs.com/redisgraph/known_limitations/) in the known limitations section, `id` can be seen as the only field that can distinguish the edges that doesn't have any `properties` and `labels` attached to them.
So Edge `Id`s will be helpful to process the relationships in the graph.
> Pass edge Id 

- redisgraph/query_result.py
Squashed Commit: 
``` 
* Assign a val to local variable `scalar` before returning
* Compare bytes of two values
```
Long:
1) There are two cases where we get an exception `UnboundLocalError: local variable 'scalar' referenced before assignment`
-  We find the type to be `boolean` and find the value not being `true` or `false` (Happens when we compare bytes with a string) and we reach the return statement and we get the above exception since we haven't defined `scalar` in the outer scope.
- When the `scalar_type` is `ResultSetScalarTypes.PROPERTY_UNKNOWN`, we reach the final statement and return `scalar` which hasn't been defined.
2) We have to compare byte response with byte string as `b'true'` is not equal to `true`, we always return the boolean values as `None` since we have reached the …
> Assign local variable `scalar` and compare bytes of two values

- redisgraph/query_result.py
- test.py
> added list/array support

- redisgraph/util.py
This PR fixes a bug in quote_string function.
The function addressed the first character in a string (`v[0]`), and cause an application crash when given an empty string.
This fix returns an empty quoted string, in case of an empty string.
> quote_string handles empty string

- redisgraph/query_result.py
In `query_result.py` between line 122 to 125. `cell` should be cast to `int` as indicated by the comment above.
> incorrect type cast in QueryResult

- redisgraph/query_result.py
- redisgraph/util.py
> add bytes type decode process

- redisgraph/edge.py
- redisgraph/query_result.py
- test.py
The original code does not support `str()` of `Edge` if the `src_node` and `dest_node` fields are not `Node`. However, the `Edge` returned from the `query` have `int` values in both `src_node` and `dest_node` fields.
I modify `__str__()`, so that it will print `()` if the `src_node` and `dest_node ` are not `Node` instances.
This PR is developed based on my last PR request #58 .
> Edge can be str() after returning from QueryResult

- redisgraph/query_result.py
- test.py
> Don't attempt to decode NULL graph entities

- redisgraph/graph.py
This fixes "TypeError: sequence item 0: expected str instance, bytes found" on line 134, in _execution_plan_to_string function in graph.py. The error occurred on python 3.6 (Ubuntu 18.04).
> resolving type error in execution_plan_to_string

- redisgraph/graph.py
Fixed syntax warning for Python 3.8.5 in line # 93.
> Fixed Python warning in graph.py

- redisgraph/graph.py
- test.py
> Add support for read_only queries

- .github/release-drafter-config.yml
- .github/workflows/check-pypi.yml
- .github/workflows/publish-pypi.yml
- .github/workflows/release-drafter.yml
This PR simplifies the release process using github actions. It follows the same approach as [redistimeseries-py](https://github.com/RedisTimeSeries/redistimeseries-py/tree/master/.github).
This PR enables automating the release draft process. On every commit to master ( and depending on the tags the PR is classified as feature, bug-fixes or maintenance). We can also ignore PRs from the release if the PR has the `skip-changelog` label.
We need to ensure that the secrets are present prior releasing ( that check action is run on every commit )
secrets required (cc @gkorland):
- `TESTPYPI_TOKEN`
- `PYPI_TOKEN`
> Added release automation (creates drafts automatically and pushes to pypi on release)

- redisgraph/graph.py
> read only procedure call

- requirements.txt
- It's way better supported and more used
- No syntax warnings as with ptable
No code changes are required
> Use prettytable instead of ptable

- redisgraph/edge.py
- redisgraph/graph.py
- redisgraph/node.py
- redisgraph/path.py
- redisgraph/query_result.py
- redisgraph/util.py
All classes in python3 are new style classes thus already inheriting
object, and python2 is not supported already since Jan 2020
> Remove inheritance from object

- redisgraph/edge.py
- redisgraph/graph.py
Asserts shall not be a part of production code, they are
stript if python is run with -o (optimization parameter)
Instead of assert use if and raise exceptions
> Remove assert statements from code base

- .circleci/config.yml
- README.md
- redisgraph/__init__.py
- redisgraph/edge.py
- redisgraph/exceptions.py
- redisgraph/graph.py
- redisgraph/node.py
- redisgraph/path.py
- redisgraph/query_result.py
- redisgraph/util.py
- test-requirements.txt
- tests/README.md
- tests/functional/test.py
- tests/functional/test_all.py
- tests/unit/test_edge.py
- tests/unit/test_graph.py
- tests/unit/test_node.py
- tests/unit/test_path.py
- tests/unit/test_query_result.py
- tests/unit/test_util.py
- tests/utils/base.py
- tox.ini
- Change structure of the repo where all tests are moved under tests/* directory 
-- All functional tests (one that exists now) are under tests/functional/* 
-- Unit tests are added under tests/unit
- Fix most of code style issues, according to the (PEP8)
- Introduce tox as helper that helps to unify testing experience (this is very very popular tool in python community, downloaded 1M+/month)
- Introduce 4 tox commands:  
- tox -e py3  to run unittests 
- tox -e pep8 to run code style checks
- tox -e cover to run unittests with coverage
- tox -e func to run existing functional tests 
- Cover with functional tests Node, Edges, Paths 
- Fix found bugs 
- Removed assserts
If this is accepted next steps are planned: 
- To cover rest of functionality with unittests
- Improve a bit code styles …
> Introduce tox, add more tests & fix bugs

- .circleci/config.yml
- test-requirements.txt
- tox.ini
It makes sense to use the same technologies locally and in CI
as it simplifies local debugging and verifing changes
Before this patch we did run sdist (bulding package) and functional
tests in CI and we were uploading coverage report to covecod
After this PR we are adding code style jobs, unittests with coverage
as well as keeping old jobs in place (but run through tox)
As well now we have 2 reports to upload one for functional tests
one for unittests
> Switch circle CI to tox

- redisgraph/edge.py
- redisgraph/graph.py
- redisgraph/query_result.py
- tests/functional/test_all.py
Map format: `[string, value_type, value, string, val_type, value ....]`
Not sure if we should change key string to a string encoded value: 
`[key_type, key, value_type, value ...]`
> map datatype

- redisgraph/graph.py
Fix: #123 
`GRAPH.RO_QUERY` is unavailable in older versions. So fallback to GRAPH.QUERY when the command is not found.
While there's a way to always use `GRAPH.QUERY` by setting `read_only` to `False`, methods that try to fetch the labels and other properties are hardcoded to `True`.
```python
def labels(self):
return self.call_procedure("db.labels", read_only=True).result_set
def relationshipTypes(self):
return self.call_procedure("db.relationshipTypes", read_only=True).result_set
def propertyKeys(self):
return self.call_procedure("db.propertyKeys", read_only=True).result_set
```
While we can have a param `read_only` to the above methods, introducing the same would actually change many methods that is calling the above methods directly or indirectly to have `read_only` param and that's …
> Fall back to GRAPH.QUERY when `GRAPH.RO_QUERY` is not available.

- pyproject.toml
> hiredis as a dependency

- redisgraph/graph.py
- tests/functional/test_all.py
Close connection on graph object destruction only when the connection was created by the constructor (bypassing host and port)
> close connection on graph destruction

- redisgraph/graph.py
- redisgraph/util.py
- tests/unit/test_util.py
* In dictionaries, keys need to _not_ be quoted.
* We process parameter values recursively, so that (nested) lists and dicts are handled.
> Support dicts in parameter values.

- README.md
Python disallows mixing tabs and spaces for indentation.
Spaces are the preferred indentation method according to [PEP 8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces).
> fix(README): convert tabs to spaces

- redisgraph/util.py
- tests/functional/test_all.py
- tests/unit/test_util.py
Fixes #139 
I added the functional test `tests.functional.test_all.TestStringMethods.test_properties_with_escapes()` which demonstrates that, when you set a property string containing backslash or quotation mark, you get the same string back after reading.
I also rewrote the unit test `tests.unit.test_util.TestUtils.test_quote_string()` using raw strings, which I think makes the test much easier to read and understand.
> Escape backslashes in parameter strings.
